"""Generate Markdown design reports."""
from datetime import datetime


def generate_markdown(problem_statement: str, architecture: dict, explanations: dict) -> str:
    nodes = architecture.get("nodes", [])
    edges = architecture.get("edges", [])
    tech_stack = architecture.get("tech_stack", [])
    summary = architecture.get("summary", "")

    lines = [
        f"# System Design: {problem_statement}",
        f"\n*Generated by StructAI on {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}*",
        "\n---\n",
        "## Overview",
        f"\n{summary}\n",
        "## Tech Stack",
        "",
        *[f"- {t}" for t in tech_stack],
        "\n---\n",
        "## Architecture Components",
        "",
    ]

    for node in nodes:
        lines.append(f"### {node['label']} (`{node['type']}`)")
        lines.append(f"\n**Technology:** {node['tech']}")
        lines.append(f"\n{node['description']}\n")

        exp = explanations.get(node["id"])
        if exp:
            lines.append(f"**Why chosen:** {exp.get('why', '')}\n")
            alts = exp.get("alternatives", [])
            if alts:
                lines.append(f"**Alternatives:** {', '.join(alts)}\n")
            lines.append(f"**Trade-offs:** {exp.get('trade_offs', '')}\n")

        lines.append("")

    lines += [
        "---\n",
        "## Data Flow",
        "",
    ]
    for edge in edges:
        src = next((n["label"] for n in nodes if n["id"] == edge["source"]), edge["source"])
        tgt = next((n["label"] for n in nodes if n["id"] == edge["target"]), edge["target"])
        lines.append(f"- **{src}** → **{tgt}** ({edge.get('label', '')})")

    return "\n".join(lines)
